from building import *

cwd = GetCurrentDir()
src = []
depend = []

CPPPATH = [cwd + '/../include']
group = []

if GetDepend(['RT_USING_MTD_NOR']):
    src += ['mtd_nor.c']
    depend += ['RT_USING_MTD_NOR']

if GetDepend(['RT_USING_MTD_NAND']):
    src += ['mtd_nand.c']
    #src += ['dev_nand.c']
    src += ['nand.c']
    src += ['ftl.c']
    depend += ['RT_USING_MTD_NAND']

if src:
    group = DefineGroup('DeviceDrivers', src, depend = depend, CPPPATH = CPPPATH)

Return('group')
